# Generated by Django 5.0.7 on 2024-07-31 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=250, verbose_name='Bezeichnug')),
                ('abbreviation', models.CharField(max_length=10, verbose_name='Abkürzung')),
                ('time', models.IntegerField(default=24, verbose_name='Dauer (Monate)')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Kommentar')),
            ],
            options={
                'verbose_name': 'Beruf',
                'verbose_name_plural': 'Berufe',
            },
        ),
        migrations.CreateModel(
            name='Lernfeld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.CharField(max_length=10, verbose_name='Nummer')),
                ('designation', models.CharField(max_length=250, verbose_name='Bezeichnug')),
                ('content', models.TextField(verbose_name='Beschreibung')),
                ('time1', models.IntegerField(verbose_name='UE 1. Lehrjahr')),
                ('time2', models.IntegerField(verbose_name='UE 1. Lehrjahr')),
                ('time3', models.IntegerField(verbose_name='UE 1. Lehrjahr')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='plan.profession', verbose_name='Beruf')),
            ],
            options={
                'verbose_name': 'Lernfeld',
                'verbose_name_plural': 'Lernfelder',
            },
        ),
    ]
