# Generated by Django 5.0.7 on 2024-07-31 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lernfeld',
            name='designation',
            field=models.CharField(max_length=250, verbose_name='Bezeichnung'),
        ),
        migrations.AlterField(
            model_name='lernfeld',
            name='time1',
            field=models.IntegerField(default=0, verbose_name='UE 1. Lehrjahr'),
        ),
        migrations.AlterField(
            model_name='lernfeld',
            name='time2',
            field=models.IntegerField(default=0, verbose_name='UE 2. Lehrjahr'),
        ),
        migrations.AlterField(
            model_name='lernfeld',
            name='time3',
            field=models.IntegerField(default=0, verbose_name='UE 3. Lehrjahr'),
        ),
        migrations.CreateModel(
            name='Lerneinheit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Bezeichnung')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('time', models.IntegerField(default=5, verbose_name='Unterichtseinheiten')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Lernfelder')),
                ('lernfeld', models.ManyToManyField(to='plan.lernfeld', verbose_name='Lernfelder')),
            ],
        ),
    ]
