# Generated by Django 5.0.7 on 2024-07-31 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_alter_lernfeld_designation_alter_lernfeld_time1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Thema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Thema')),
                ('description', models.TextField(verbose_name='Beschreibung')),
            ],
            options={
                'verbose_name': 'Thema',
                'verbose_name_plural': 'Themas',
            },
        ),
        migrations.AlterField(
            model_name='lerneinheit',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
    ]
