# Generated by Django 5.0.7 on 2024-08-01 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_thema_alter_lerneinheit_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lerneinheit',
            options={'verbose_name': 'Lerneinheit', 'verbose_name_plural': 'Lerneinheiten'},
        ),
        migrations.AlterModelOptions(
            name='thema',
            options={},
        ),
        migrations.AddField(
            model_name='lerneinheit',
            name='possible',
            field=models.ManyToManyField(related_name='possib', to=settings.AUTH_USER_MODEL, verbose_name='mögliche Ausbilder'),
        ),
        migrations.AlterField(
            model_name='lerneinheit',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
    ]
