# Generated by Django 5.0.7 on 2024-08-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0005_lerneinheit_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='lerneinheit',
            name='position',
            field=models.IntegerField(default=0, verbose_name='Reihenfolge'),
        ),
    ]
