# Generated by Django 5.2 on 2025-04-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beruf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.CharField(max_length=10, verbose_name='Kürzel')),
                ('description', models.TextField(verbose_name='Beschreibung')),
            ],
            options={
                'verbose_name': 'Beruf',
                'verbose_name_plural': 'Berufe',
            },
        ),
        migrations.CreateModel(
            name='Lehrplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lernfeld', models.CharField(max_length=10, verbose_name='Lernfeld')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('duration', models.IntegerField(default=30, verbose_name='Dauer')),
                ('kernkompetenz', models.TextField(verbose_name='Kernkompetenz')),
                ('profession', models.ManyToManyField(to='app1.beruf', verbose_name='Beruf')),
            ],
            options={
                'verbose_name': 'Lehrplan',
                'verbose_name_plural': 'Lehrpläne',
            },
        ),
    ]
