# Generated by Django 5.2 on 2025-04-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LPDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aim', models.TextField(verbose_name='kompetenzbasierte Ziele')),
                ('congrete', models.TextField(blank=True, null=True, verbose_name='Konkretisierung')),
                ('situation', models.TextField(verbose_name='Lernsituation')),
                ('result', models.CharField(max_length=50, verbose_name='Handlungsergebnis')),
                ('competence', models.TextField(verbose_name='Handlungsergebnisüberfachliche Kompetenzen')),
                ('notes', models.CharField(max_length=50, verbose_name='Hinweise')),
                ('time', models.IntegerField(verbose_name='Zeit')),
            ],
            options={
                'verbose_name': 'LPDetail',
                'verbose_name_plural': 'LPDetails',
                'ordering': ['situation'],
            },
        ),
        migrations.AlterModelOptions(
            name='lehrplan',
            options={'ordering': ['lernfeld'], 'verbose_name': 'Lehrplan', 'verbose_name_plural': 'Lehrpläne'},
        ),
        migrations.AddField(
            model_name='lehrplan',
            name='year',
            field=models.IntegerField(default=1, verbose_name='Jahr'),
        ),
    ]
