# Generated by Django 5.2 on 2025-04-15 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_lpdetail_alter_lehrplan_options_lehrplan_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='lpdetail',
            name='plan',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app1.lehrplan', verbose_name='Lernfeld'),
            preserve_default=False,
        ),
    ]
