# Generated by Django 5.2 on 2025-04-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_lpdetail_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lpdetail',
            options={'ordering': ['plan', 'situation'], 'verbose_name': 'LPDetail', 'verbose_name_plural': 'LPDetails'},
        ),
        migrations.AlterField(
            model_name='lpdetail',
            name='competence',
            field=models.TextField(verbose_name='überfachliche Kompetenzen'),
        ),
        migrations.AlterField(
            model_name='lpdetail',
            name='notes',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Hinweise'),
        ),
    ]
